### ISSUE TITLE
xunit 2.4.0

### ISSUE THREAD

**Issue by cveld** [DjvuNet/DjvuNet#124]
Are you planning to implement xunit 2.4.0?
We noticed that the two classes within 
DjvuNet\DjvuNet.Shared.Tests\xunit
1. DjvuDataRowTestCase.cs
2. DjvuNamedDataRowTestCase.cs

do not implement the property Timeout.

**Comment by 4creators** [comment]
Closing as xunit 2.4.0 support was merged with PR #126 to master
